export const products = [
    {
        id: 1,
        categoryId: 1,
        name: 'Galaxy 100',
        desc: 'Xe đạp Galaxy',
        price: 3690000,
        discount: 13,
        createdAt: '2024-12-26',
    },
    {
        id: 2,
        categoryId: 1,
        name: 'Xe đạp Galaxy mẫu 2',
        desc: 'Xe đạp Galaxy',
        price: 3690000,
        discount: 0,
        createdAt: '2024-12-20',
    },
    {
        id: 3,
        categoryId: 2,
        name: 'Xe đạp nhập khẩu cao cấp',
        desc: 'Xe đạp nhập khẩu',
        price: 4990000,
        discount: 10,
        createdAt: '2024-12-15',
    },
    {
        id: 4,
        categoryId: 3,
        name: 'Xe đạp trẻ em Galaxy',
        desc: 'Xe đạp trẻ em',
        price: 2490000,
        discount: 0,
        createdAt: '2024-12-10',
    },
    {
        id: 5,
        categoryId: 3,
        name: 'Xe đạp trẻ em Galaxy mẫu 2',
        desc: 'Xe đạp trẻ em',
        price: 2490000,
        discount: 0,
        createdAt: '2024-11-30',
    },
    {
        id: 6,
        categoryId: 4,
        name: 'Xe đạp trẻ em Galaxy mẫu 2',
        desc: 'Xe đạp trẻ em',
        price: 2490000,
        discount: 0,
        createdAt: '2024-11-30',
    },
    {
        id: 7,
        categoryId: 4,
        name: 'Xe đạp trẻ em Galaxy mẫu 2',
        desc: 'Xe đạp trẻ em',
        price: 2490000,
        discount: 0,
        createdAt: '2024-11-30',
    },
    {
        id: 8,
        categoryId: 4,
        name: 'Xe đạp trẻ em Galaxy mẫu 2',
        desc: 'Xe đạp trẻ em',
        price: 2490000,
        discount: 0,
        createdAt: '2024-11-30',
    },
    {
        id: 9,
        categoryId: 4,
        name: 'Xe đạp trẻ em Galaxy mẫu 2',
        desc: 'Xe đạp trẻ em',
        price: 2490000,
        discount: 0,
        createdAt: '2024-11-30',
    },
];
