export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Profile } from './Profile';
export { default as Detail } from './DetailProduct';
export { default as Searched } from './Searched';
// export { default as Collection } from './Collection';
export { default as Category } from './Category';
export { default as Collection } from './Category_Demo';
export { default as Cart } from './Cart';
export { default as OrderHistory } from './OrderHistory';
export { default as DetailOrderHistory } from './DetailOrderHistory';
